name: TheMonkeyHouseMedia
favicon: null
layout_spectrum: 0.11283415509387851
typography_spectrum: 0.3978626192547381
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.40475622611120343
  lightness: 0.8355900838505477
  saturation: 0.736802343511954
  rhythmicContrast: 0.7545764707028866
purpose: []
