name: The MonkeyHouse Media
favicon: null
layout_spectrum: 0.3443
typography_spectrum: 0.5642
title: Sean W. Makiney and all things Monkey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1e0000'
    - '#350001'
    - '#530103'
    - '#710206'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
